### ISSUE TITLE
referit_edgeboxes_top100.zip

### ISSUE THREAD

**Issue by SnowFlowerQW** [ronghanghu/text_objseg#8]
the link of referit_edgeboxes_top100 is invaliable, could you please release a validate link,thank you

**Comment by ronghanghu** [comment]
Hi, sorry that the links have expired. I've uploaded the referit dataset and edge boxes to https://drive.google.com/drive/folders/12EEft_mg-47EwWegawyH0pHaX7781E3_?usp=sharing

**Comment by SnowFlowerQW** [comment]
Hi, thanks. The links of vgg_params.npz, referit_fc8_det_iter_25000.tfmodel, referit_fc8_seg_lowres_iter_30000.tfmodel, referit_fc8_seg_highres_iter_18000.tfmodel, are invaliable. Could you please also release a validate link, thank you.

**Comment by ronghanghu** [comment]
Hi, I've uploaded them here: https://drive.google.com/drive/folders/1rPYln_jsC12Q0AQNf0pJKKseXvPA7-zg
